services:
  redis_db:
    image: redis:7.4-alpine3.21
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data:/data
    networks:
      - custom_network

  mongo_db:
    image: mongo:5.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    command: mongod --noauth
    volumes:
      - ./data/mongodb_data:/data/db
      - ./data/common/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - custom_network

  backend_bot:
    container_name: backend_bot
    build:
      context: ./backend_bot
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - redis_db
      - mongo_db
    env_file:
      - ./backend_bot/.env
    networks:
      - custom_network

  backend_one:
    container_name: backend_one
    build:
      context: ./backend_one
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - redis_db
      - backend_bot
    env_file:
      - ./backend_one/.env
    networks:
      - custom_network
  
  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   volumes:
  #     - ./nginx/templates:/etc/nginx/templates
  #     - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   environment:
  #     - NGINX_HOST=foobar.com
  #     - NGINX_PORT=80
  #   depends_on:
  #     - backend_one
  #     - backend_bot
  #   networks:
  #     - custom_network

networks:
  custom_network:
    driver: bridge

volumes:
  redis_data:
  mongodb_data:
    driver: local